// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwZ-GGqbpRagtgAiNYnavF7qvlJsDK3vk',
    appId: '1:279526850355:web:c6128c5fd4d03814db4846',
    messagingSenderId: '279526850355',
    projectId: 'task-app-1eb48',
    authDomain: 'task-app-1eb48.firebaseapp.com',
    storageBucket: 'task-app-1eb48.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4lMRNzyREsu8uwfft1CLQjh2nkyxxHDs',
    appId: '1:279526850355:android:59e69ede20125025db4846',
    messagingSenderId: '279526850355',
    projectId: 'task-app-1eb48',
    storageBucket: 'task-app-1eb48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSe-wF4_CGGBa-cbq2HKdMqGOSPydUNvY',
    appId: '1:279526850355:ios:8118bdb4b9554c2cdb4846',
    messagingSenderId: '279526850355',
    projectId: 'task-app-1eb48',
    storageBucket: 'task-app-1eb48.appspot.com',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSe-wF4_CGGBa-cbq2HKdMqGOSPydUNvY',
    appId: '1:279526850355:ios:b2c8384acc53c045db4846',
    messagingSenderId: '279526850355',
    projectId: 'task-app-1eb48',
    storageBucket: 'task-app-1eb48.appspot.com',
    iosBundleId: 'com.example.taskApp.RunnerTests',
  );
}
